<?php

namespace Database\Seeders;

use App\Http\Controllers\Address\DistrictController;
use App\Models\Board;
use App\Models\District;
use App\Models\Examination;
use App\Models\PassingYear;
use App\Models\Subject;
use App\Models\Unit;
use Carbon\Carbon;
use Carbon\Factory;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EduactionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
       Examination::create(['name'=>'JSC']);
       Examination::create(['name'=>'SSC']);
       Examination::create(['name'=>'HSC']);
       Unit::create(['name'=>'A']);
       Unit::create(['name'=>'B']);
       Unit::create(['name'=>'C']);
       Unit::create(['name'=>'D']);
       for($i=1970;$i<=Carbon::now()->year;$i++){
            PassingYear::create(['name'=>$i]);
       }
      $boards=['Dhaka',' Rajshahi','Comilla','Jessore','Chittagong','Barisal','Sylhet','Bangladesh Madrasah Education Board'];
     foreach($boards as $board)
     {
         Board::create(['name'=>$board]);
     }
      $subjects=['Bachelor of Architecture (B.Arch.)',
                'Bachelor of Arts (B.A.)',
                'Bachelor of Business (B.B.)',
                'Bachelor of Business Administration (B.B.A.)',
                'Bachelor of Science in Business (B.S.B.)',
                'Bachelor of Canon Law (B.C.L.)',
                'Bachelor of Computer Science (B.C.S.)',
                'Bachelor of Science in Computer Science (B.S.C.S.)',
                'Bachelor of Criminal Justice (B.C.J.)',
                'Bachelor of Science in Criminal Justice (B.S.C.J.)',
                'Bachelor of Divinity (B.D.)',
                'Bachelor of Education (B.Ed.)',
                'Bachelor of Science in Education (B.S.Ed.)',
                'Bachelor of Wireless Engineering (B.W.E.)',
                'Bachelor of Engineering (B.E./B.Eng.)',
                'Bachelor of Science in Engineering (B.S.E./B.S.EN.)',
                'Bachelor of Science in Aerospace Engineering (B.S.A.E.)',
                'Bachelor of Science in Agricultural Engineering (B.S.A.E.)',
                'Bachelor of Science in Biological Systems (B.S.B.S.)',
                'Bachelor of Science in Biosystems and Agricultural Engineering (B.S.B.A.E.)',
                'Bachelor of Science in Biological Engineering (B.S.B.E.)',
                'Bachelor of Biomedical Engineering (B.B.m.E.)',
                'Bachelor of Science in Biomedical Engineering (B.S.B.E./B.S.B.M.E.)',
                'Bachelor of Science in Chemical Engineering (B.S.Ch.E.)',
                'Bachelor of Science in Chemical and Biomolecular Engineering (B.S.Ch.B.E.)',
                'Bachelor of Science in Chemical and Materials Engineering (B.S.C.M.E.)',
                'Bachelor of Civil Engineering (B.C.E.)',
                'Bachelor of Science in Civil Engineering (B.S.C.E.)',
                'Bachelor of Science in Civil and Infrastructure Engineering (B.S.-C.I.E.)',
                'Bachelor of Computer Engineering (B.Comp.E.)',
                'Bachelor of Science in Computer Engineering (B.S.C.E./B.S.Cmp.E.)',
                'Bachelor of Science in Computer Science and Engineering (B.S.C.S.E.)',
                'Bachelor of Science in Electrical and Computer Engineering (B.S.E.C.E.)',
                'Bachelor of Electrical Engineering (B.E.E.)',
                'Bachelor of Science in Electrical Engineering (B.S.E.E.)',
                'Bachelor of Science in Engineering Management (B.S.E.Mgt.)',
                'Bachelor of Science in Environmental Engineering (B.S.En.E./B.S.Env.E.)',
                'Bachelor of Fiber Engineering (B.F.E.)',
                'Bachelor of Science in Industrial Engineering (B.S.I.E.)',
                'Bachelor of Science in Manufacturing Engineering (B.S.Mfg.E.)',
                'Bachelor of Science in Manufacturing Systems Engineering (B.S.M.S.E.)',
                'Bachelor of Science in Materials Science and Engineering (B.S.M.S.E.)',
                'Bachelor of Science in Materials Engineering (B.S.MA.E.)',
                'Bachelor of Mechanical Engineering (B.M.E.)',
                'Bachelor of Science in Mechanical Engineering (B.S.M.E.)',
                'Bachelor of Science in Metallurgical Engineering (B.S.Mt.E.)',
                'Bachelor of Science in Mining Engineering (B.S.MI.E.)',
                'Bachelor of Science in Systems (B.S.-SYST.)',
                'Bachelor of Software Engineering (B.S.W.E.)',
                'Bachelor of Science in Software Engineering (B.S.S.E.)',
                'Bachelor of Systems Engineering (B.S.E.)',
                'Bachelor of Science in Systems Engineering (B.S.S.E.)',
                'Bachelor of Engineering Technology (B.E.T.)',
                'Bachelor of Science in Engineering Technology (B.S.E.T.)',
                'Bachelor of Science in Civil Engineering Technology (B.S.C.E.T./B.S.Civ.E.T.)',
                'Bachelor of Science in Computer Engineering Technology (B.S.C.E.T.)',
                'Bachelor of Science in Construction Engineering Technology (B.S.Con.E.T.)',
                'Bachelor of Science in Drafting Design Technology (B.S.D.D.T.)',
                'Bachelor of Science in Electrical/Electronics Technology (B.S.E.T.)',
                'Bachelor of Science in Electrical Engineering Technology (B.S.E.E.T.)',
                'Bachelor of Science in Electro-Mechanical Engineering Technology (B.S.E.M.E.T.)',
                'Bachelor of Science in Mechanical Engineering Technology (B.S.M.E.T.)',
                'Bachelor of Fine Arts (B.F.A.)',
                'Bachelor of Forestry (B.F.)',
                'Bachelor of Science in Forest Research (B.S.For.Res.)',
                'Bachelor of Hebrew Letters (B.H.L.)',
                'Bachelor of Journalism (B.J.)',
                'Bachelor of Laws (LL.B.)',
                'Bachelor of Liberal Studies (B.L.S.)',
                'Bachelor of Literature (B.Lit.)',
                'Bachelor of Marine Science (B.M.S.)',
                'Bachelor of Music (B.M.)',
                'Bachelor of Nursing (B.N.)',
                'Bachelor of Science in Nursing (B.S.N.)',
                'Bachelor of Pharmacy (B.Pharm.)',
                'Bachelor of Philosophy (B.Phil.)',
                'Bachelor of Religious Education (B.R.E.)',
                'Bachelor of Science (B.S.)',
                'Bachelor of Science in Chemistry (B.S.Ch.)',
                'Bachelor of Technology (B.T./B.Tech.)',
                'Master of Accountancy',
                'Master of Advanced Study',
                'Masters of Agricultural Economics',
                'Master of Applied Finance',
                'Master of Applied Science',
                'Master of Architecture',
                'Master of Arts',
                'Master of Arts in Liberal Studies',
                'Master of Arts in Special Education',
                'Master of Arts in Teaching',
                'Master of Bioethics',
                'Master of Business Administration',
                'Master of Business, Entrepreneurship and Technology',
                'Master of Business',
                'Master of Business Engineering',
                'Master of Business Informatics',
                'Master of Chemistry',
                'Master of Christian Education',
                'Master of City Planning',
                'Master of Commerce',
                'Master of Computational Finance',
                'Master of Computer Applications',
                'Master of Counselling',
                'Master of Criminal Justice',
                'Master of Creative Technologies',
                'Master of Data Science',
                'Master of Defence Studies',
                'Master of Design',
                'Masters of Development Economics',
                'Master of Divinity',
                'Master of Economics',
                'Master of Education',
                'Master of Engineering',
                'Master of Engineering Management',
                'Master of Enterprise',
                'Master of European Law',
                'Master of Finance',
                'Master of Financial Economics',
                'Master of Financial Engineering',
                'Master of Financial Mathematics',
                'Master of Fine Arts',
                'Master of Health Administration',
                'Master of Health Economics',
                'Master of Health Science',
                'Master of Humanities',
                'Master of Industrial and Labor Relations',
                'Master of International Affairs',
                'Master of International Business',
                'Masters of International Economics',
                'Master of International Studies',
                'Master of Information and Cybersecurity',
                'Master of Information and Data Science',
                'Master of Information Management',
                'Master of Information System Management',
                'Master of Journalism',
                'Master of Jurisprudence',
                'Master of Laws',
                'Master of Mass Communication',
                'Master of Studies in Law',
                'Master of Landscape Architecture',
                'Master of Letters',
                'Master of Liberal Arts',
                'Master of Library and Information Science',
                'Master of Management',
                'Master of Management of Innovation',
                'Master of Mathematical Finance',
                'Master of Mathematics',
                'Master of Medical Science',
                'Master of Medicine',
                'Masters of Military Art and Science',
                'Master of Military Operational Art and Science',
                'Master of Ministry',
                'Master of Music',
                'Master of Music Education',
                'Master of Occupational Behaviour and Development',
                'Master of Occupational Therapy',
                'Master of Pharmacy',
                'Master of Philosophy',
                'Master of Physician Assistant Studies',
                'Master of Physics',
                'Master of Political Science',
                'Master of Professional Studies',
                'Master of Psychology',
                'Master of Public Administration',
                'Master of Public Affairs',
                'Master of Public Health',
                'Master of Public Management',
                'Master of Public Policy',
                'Master of Public Relations',
                'Master of Public Service',
                'Master of Quantitative Finance',
                'Master of Rabbinic Studies',
                'Master of Real Estate Development',
                'Master of Religious Education',
                'Master of Research',
                'Master of Sacred Music',
                'Master of Sacred Theology',
                'Master of Science',
                'Master of Science in Administration',
                'Master of Science in Archaeology',
                'Master of Science in Biblical Archaeology',
                'Master of Science in Bioinformatics',
                'Master of Science in Computer Science',
                'Master of Science in Counselling',
                'Master of Science in Cyber Security',
                'Master of Science in Engineering',
                'Master of Science in Development Administration',
                'Master of Science in Finance',
                'Master of Science in Health Informatics',
                'Master of Science in Human Resource Development',
                'Master of Science in Information Assurance',
                'Master of Science in Information Systems',
                'Master of Science in Information Technology',
                'Master of Science in Leadership',
                'Master of Science in Management',
                'Master of Science in Nursing',
                'Master of Science in Project Management',
                'Master of Science in Supply Chain Management',
                'Master of Science in Teaching',
                'Master of Science in Taxation',
                'Master of Social Science',
                'Master of Social Work',
                'Master of Strategic Studies',
                'Master of Studies',
                'Master of Surgery',
                'Master of Talmudic Law',
                'Master of Taxation',
                'Master of Theological Studies',
                'Master of Technology',
                'Master of Theology',
                'Master of Urban Planning',
                'Master of Veterinary Science'
            ];

    foreach($subjects as $subject)
        {
            Subject::create(['name'=>$subject]);
        }
        $districts=[
                'Dhaka',
                'Faridpur',
                'Gazipur',
                'Gopalganj',
                'Jamalpur',
                'Kishoreganj',
                'Madaripur',
                'Manikganj',
                'Munshiganj',
                'Mymensingh',
                'Narayanganj',
                'Narsingdi',
                'Netrokona',
                'Rajbari',
                'Shariatpur',
                'Sherpur',
                'Tangail',
                'Bogra',
                'Joypurhat',
                'Naogaon',
                'Natore',
                'Nawabganj',
                'Pabna',
                'Rajshahi',
                'Sirajgonj',
                'Dinajpur',
                'Gaibandha',
                'Kurigram',
                'Lalmonirhat',
                'Nilphamari',
                'Panchagarh',
                'Rangpur',
                'Thakurgaon',
                'Barguna',
                'Barisal',
                'Bhola',
                'Jhalokati',
                'Patuakhali',
                'Pirojpur',
                'Bandarban',
                'Brahmanbaria',
                'Chandpur',
                'Chittagong',
                'Comilla',
                'Coxs Bazar',
                'Feni',
                'Khagrachari',
                'Lakshmipur',
                'Noakhali',
                'Rangamati',
                'Habiganj',
                'Maulvibazar',
                'Sunamganj',
                'Sylhet',
                'Bagerhat',
                'Chuadanga',
                'Jessore',
                'Jhenaidah',
                'Khulna',
                'Kushtia',
                'Magura',
                'Meherpur',
                'Narail',
                'Satkhira'];
                foreach($districts as $district)
                {
                    District::create(['name'=>$district]);
                }

      DB::table('universities')->insert([
          [
          'name'=>'University of Dhaka',
          'location'=>'Dhaka University, Ramna, Dhaka-1000'
          ],[
              'name'=> 'University of Rajshahi',
              'location'=>'Motihar, Kajla, Rajshahi-6205'
          ],[
             'name'=> 'Bangladesh Agricultural University',
             'location'=>'Bangladesh Agricultural University, Mymensingh-2202, Bangladesh'
          ],
       [
          'name'=> 'Bangladesh University of Engineering & Technology',
          'location'=>'Bangladesh University of Engineering & Technology,Dhaka-1000, Bangladesh'
       ],[
          'name'=> 'University of Chittagong',
          'location'=>'Village: Fatepur, Post Office: University of Chittagong, Upazilla: Hathazari, District: Chattogram'
       ]]);

        // 'Jahangirnagar University',
        // 'Islamic University, Bangladesh',
        // 'Shahjalal University of Science & Technology',
        // 'Khulna University',
        // 'National University',
        // 'Bangladesh Open University',
        // 'Bangabandhu Sheikh Mujib Medical University',
        // 'Bangabandhu Sheikh Mujibur Rahman Agricultural University',
        // 'Hajee Mohammad Danesh Science & Technology University',
        // 'Mawlana Bhashani Science & Technology University',
        // 'Patuakhali Science And Technology University',
        // 'Sher-e-Bangla Agricultural University',
        // 'Chittagong University of Engineering & Technology',
        // 'Rajshahi University of Engineering & Technology',
        // 'Khulna University of Engineering & Technology',
        // 'Dhaka University of Engineering & Technology',
        // 'Noakhali Science & Technology University',
        // 'Jagannath University',
        // 'Comilla University',
        // 'Jatiya Kabi Kazi Nazrul Islam University',
        // 'Chittagong Veterinary and Animal Sciences University',
        // 'Sylhet Agricultural University',
        // 'Jessore University of Science & Technology',
        // 'Pabna University of Science and Technology',
        // 'Begum Rokeya University, Rangpur',
        // 'Bangladesh University of Professionals',
        // 'Bangabandhu Sheikh Mujibur Rahman Science & Technology University',
        // 'Bangladesh University of Textiles',
        // 'University of Barisal',
        // 'Rangamati Science and Technology University',
        // 'Bangabandhu Sheikh Mujibur Rahman Maritime University , Bangladesh',
        // 'Islamic Arabic University',
        // 'Chittagong Medical University',
        // 'Rajshahi Medical University',
        // 'Rabindra University, Bangladesh',
        // 'Bangabandhu Sheikh Mujibur Rahman Digital University, Bangladesh',
        // 'Sheikh Hasina University',
        // 'Khulna Agricultural University',
        // 'Bangamata Sheikh Fojilatunnesa Mujib Science and Technology University',
        // 'Sylhet Medical University',
        // 'Bangabandhu Sheikh Mujibur Rahman Aviation And Aerospace University (BSMRAAU)',
        // 'Chandpur Science and Technology University',
        // 'Bangabandhu Sheikh Mujibur Rahman University, Kishoreganj',
        // 'Hobiganj Agricultural University',
        // 'Sheikh Hasina Medical University, Khulna'];
    }

}
